apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthservices-app-deploy
  labels:
    app: healthservices-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: healthservices-app
  template:
    metadata:
      labels:
        app: healthservices-app
    spec:
      containers:
      - name: healthservices-app-container
        image: paragv14/healthservices-app
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: healthservices-app-np-service
  labels:
    app: healthservices-app
spec:
  selector:
    app: healthservices-app

  type: NodePort
  ports:
  - nodePort: 31036
    port: 8082
    targetPort: 8082
