apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-eta-app-deploy
  labels:
    app: healthcare-eta-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: healthcare-eta-app
  template:
    metadata:
      labels:
        app:healthcare-eta-app
    spec:
      containers:
      - name: healthcare-eta-app-container
        image: paragv14/healthcareapp-app
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: healthcare-eta-app-np-service
  labels:
    app: healthcare-eta-app
spec:
  selector:
    app:healthcare-eta-app

  type: NodePort
  ports:
  - nodePort: 31030  
    port: 8082
    targetPort: 8082
