apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-app-deploy
  labels:
    app: health-tech-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: health-tech-app
  template:
    metadata:
      labels:
        app: health-tech-app
    spec:
      containers:
      - name: healthcareapp-container
        image: paragv14/health-tech-app
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: healthcareapp-np-service
  labels:
    app: health-tech-app
spec:
  selector:
    app: health-tech-app

  type: NodePort
  ports:
  - nodePort: 31030  
    port: 8082
    targetPort: 8082
